gui:
  theme:
    activeBorderColor:
      - "#8ba4b0" # dragonBlue (Kanagawa Dragon)
      - bold
    inactiveBorderColor:
      - "#a6a69c" # dragonGray (приглушенный текст)
    optionsTextColor:
      - "#c5c9c5" # dragonWhite (текст)
    selectedLineBgColor:
      - "#282727" # dragonBlack4 (выделение)
    cherryPickedCommitBgColor:
      - "#8ea4a2" # dragonAqua
    cherryPickedCommitFgColor:
      - "#c5c9c5" # dragonWhite (текст)
    unstagedChangesColor:
      - "#c4746e" # dragonRed (красный)
    searchingActiveBorderColor:
      - "#c4b28a" # dragonYellow (золотой)
  nerdFontsVersion: "3"
  showIcons: true
  expandFocusedSidePanel: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium"
  overrideGpg: false      # установите в true если у вас проблемы с GPG
os:
  editCommand: 'nvim'     # измените на свой предпочитаемый редактор
  editCommandTemplate: '{{editor}} {{filename}}'
  openCommand: 'xdg-open {{filename}}' # для Linux
  # openCommand: 'open {{filename}}'   # для macOS
  # openCommand: 'start {{filename}}'  # для Windows

refresher:
  refreshInterval: 3       # интервал обновления в секундах
  fetchInterval: 60        # интервал fetch в секундах
