gui:
  theme:
    activeBorderColor:
      - "#c4a7e7" # магента (Rose Pine Moon)
      - bold
    inactiveBorderColor:
      - "#908caa" # приглушенный текст
    optionsTextColor:
      - "#e0def4" # текст
    selectedLineBgColor:
      - "#393552" # выделение (Moon)
    cherryPickedCommitBgColor:
      - "#9ccfd8" # голубой
    cherryPickedCommitFgColor:
      - "#e0def4" # текст
    unstagedChangesColor:
      - "#eb6f92" # красный
    searchingActiveBorderColor:
      - "#f6c177" # золотой
  nerdFontsVersion: "3"
  showIcons: true
  expandFocusedSidePanel: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium"
  overrideGpg: false      # установите в true если у вас проблемы с GPG
os:
  editCommand: 'nvim'     # измените на свой предпочитаемый редактор
  editCommandTemplate: '{{editor}} {{filename}}'
  openCommand: 'xdg-open {{filename}}' # для Linux
  # openCommand: 'open {{filename}}'   # для macOS
  # openCommand: 'start {{filename}}'  # для Windows

refresher:
  refreshInterval: 3       # интервал обновления в секундах
  fetchInterval: 60        # интервал fetch в секундах
